SPORE_AMOUNT: 1
CELL_SEGMENT_LENGTH: 1
GROWTH_SPEED: 10
ANGLE_DEVIATION_PER_MICRON: 20
CROWDING_SLOPE_STEEPNESS: 8
CROWDING_INTENSITY: 0.01
ERROR_TOLERANCE: 0.001
TROPISM_INTENSITY: 0
TROPISM_BEND_PER_MICRON: 20
FRAGMENT_THRESHOLD: 200
FRAGMENT_RATE: 0.001