SPORE_AMOUNT: 10
CELL_SEGMENT_LENGTH: 1
GROWTH_SPEED: 10
ANGLE_DEVIATION_PER_MICRON: 20
CROWDING_SLOPE_STEEPNESS: 10
CROWDING_INTENSITY: 0.05
ERROR_TOLERANCE: 0.001
TROPISM_INTENSITY: 0
TROPISM_BEND_PER_MICRON: 20